### ISSUE TITLE
Action detail screen 

### ISSUE THREAD

**Issue by SamUndefined** [actworthy/citizen-flutter#28]
When an action is tapped, the app should open a screen detailing the action. This screen is specified in the [UI mockups pdf](https://github.com/actworthy/citizen-flutter/blob/master/mobile-design.pdf)

**Comment by SamUndefined** [comment]
Some actions may have Pictures in the future, others will not. Right now, none are being returned so no need to worry about the pictures themselves just yet

**Comment by ghost** [comment]
I'd like to work on this issue.
